api_url: "https://api.example.com"
poll_interval: 60
log_level: "info"
log_path: "/var/log/crossplatformagent/crossplatformagent.log"
log_dir: "/var/log/crossplatformagent/"
agent_id: "your_agent_id"
agent_password: "your_agent_password"
